In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached h5py-3.11.0-cp38-cp38-win_amd64.whl.metadata (2.5 kB)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.whl.metadata (14 kB)
  Using cached google_auth-2.32.0-py2.py3-none-any.whl.metadata (4.7 kB)

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.



   ------------------- -------------------- 132.6/276.5 MB 4.5 MB/s eta 0:00:33
   ------------------- -------------------- 132.9/276.5 MB 4.5 MB/s eta 0:00:33
   ------------------- -------------------- 133.1/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 133.2/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 133.4/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 133.6/276.5 MB 4.3 MB/s eta 0:00:33
   ------------------- -------------------- 133.9/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 134.0/276.5 MB 4.3 MB/s eta 0:00:33
   ------------------- -------------------- 134.3/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 134.5/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 134.8/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- -------------------- 135.0/276.5 MB 4.4 MB/s eta 0:00:33
   ------------------- ----------------

In [3]:
import tensorflow as tf

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=500

In [8]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[99, 423, 107, 67], [99, 423, 107, 141], [99, 317, 107, 45], [491, 222, 139, 366, 192], [491, 222, 139, 366, 81], [141, 99, 240, 107, 380], [404, 467, 490, 366]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  99 423 107  67]
 [  0   0   0   0  99 423 107 141]
 [  0   0   0   0  99 317 107  45]
 [  0   0   0 491 222 139 366 192]
 [  0   0   0 491 222 139 366  81]
 [  0   0   0 141  99 240 107 380]
 [  0   0   0   0 404 467 490 366]]


In [12]:
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size, 10 , input_length=sent_length))
model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 5s 5s/step


array([[-0.0222435 , -0.03895675,  0.03337976, -0.03448895, -0.03434749,
         0.03117492, -0.02950348,  0.03980652,  0.0143091 ,  0.00443835],
       [-0.0222435 , -0.03895675,  0.03337976, -0.03448895, -0.03434749,
         0.03117492, -0.02950348,  0.03980652,  0.0143091 ,  0.00443835],
       [-0.0222435 , -0.03895675,  0.03337976, -0.03448895, -0.03434749,
         0.03117492, -0.02950348,  0.03980652,  0.0143091 ,  0.00443835],
       [-0.0222435 , -0.03895675,  0.03337976, -0.03448895, -0.03434749,
         0.03117492, -0.02950348,  0.03980652,  0.0143091 ,  0.00443835],
       [ 0.01769242, -0.04868242,  0.04776721, -0.00223324,  0.00805204,
        -0.02505715, -0.04164707, -0.03124276,  0.04965052, -0.02837104],
       [ 0.01841595, -0.03947874, -0.03400017, -0.01778486,  0.01615204,
        -0.02937064, -0.00020485,  0.04953429, -0.01193495, -0.02158631],
       [-0.02082433,  0.0213205 ,  0.00528198, -0.02330752,  0.0089286 ,
        -0.04084742,  0.03906958, -0.01289134

In [16]:
sentences=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [17]:
onehot_representation = [one_hot(words, voc_size) for words in sentences]
print(onehot_representation)

[[99, 122, 382, 139, 317, 303], [200, 487, 382, 61, 265, 446], [491, 495, 358, 49], [99, 131, 382, 327, 99, 184], [451, 321, 186, 382, 61, 265, 446], [228, 382, 61, 265, 267, 441]]


In [19]:
embedded_documents = pad_sequences(onehot_representation, padding='pre', maxlen=sent_length)
print(embedded_documents)

[[  0   0  99 122 382 139 317 303]
 [  0   0 200 487 382  61 265 446]
 [  0   0   0   0 491 495 358  49]
 [  0   0  99 131 382 327  99 184]
 [  0 451 321 186 382  61 265 446]
 [  0   0 228 382  61 265 267 441]]


In [22]:
model1 = Sequential()
model1.add(Embedding(voc_size, 15, input_length=sent_length))
model1.compile('adam','mse')

In [23]:
model1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 15)             7500      
                                                                 
Total params: 7500 (29.30 KB)
Trainable params: 7500 (29.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
model1.predict(embedded_documents[2])

1/1 [==============================] - 0s 89ms/step


array([[-0.03140934, -0.04594851,  0.03223235,  0.04684037,  0.00161861,
        -0.01681172,  0.01100872,  0.00743137,  0.00162204,  0.04451146,
         0.0470593 ,  0.00638326, -0.04955554, -0.01792866, -0.04500967],
       [-0.03140934, -0.04594851,  0.03223235,  0.04684037,  0.00161861,
        -0.01681172,  0.01100872,  0.00743137,  0.00162204,  0.04451146,
         0.0470593 ,  0.00638326, -0.04955554, -0.01792866, -0.04500967],
       [-0.03140934, -0.04594851,  0.03223235,  0.04684037,  0.00161861,
        -0.01681172,  0.01100872,  0.00743137,  0.00162204,  0.04451146,
         0.0470593 ,  0.00638326, -0.04955554, -0.01792866, -0.04500967],
       [-0.03140934, -0.04594851,  0.03223235,  0.04684037,  0.00161861,
        -0.01681172,  0.01100872,  0.00743137,  0.00162204,  0.04451146,
         0.0470593 ,  0.00638326, -0.04955554, -0.01792866, -0.04500967],
       [-0.00428374, -0.00803118, -0.04418795, -0.03178289,  0.013825  ,
         0.02989537, -0.04212205, -0.04584767, 